### ISSUE TITLE
Reversed results with imshow

### ISSUE THREAD

**Issue by frederictost** [hojunkim13/PINNs#1]
Hello,

I've been impressed by the job you have made about PINNs. The cases you are presenting are **symmetric** about the x-axis and the bug I've found is hidden.
With Matplotlib you have to add **origin='lower'** if you want to get the relevant plot.
`im = ax.imshow(data[i], cmap="rainbow", extent=[x_min, x_max, y_min, y_max], origin='lower')`

Regards

Frédéric

**Comment by hojunkim13** [comment]
I hadn't noticed it, I just added the argument. Thanks for your comments.
